### ISSUE TITLE
The coding environment -- python version

### ISSUE THREAD

**Issue by yulinliutw** [akar43/lsm#11]
Hello! Thank you for sharing your research.
When I use the python 3.5 to run your code, It has some error come from python version.
EX:  AttributeError: 'dict' object has no attribute 'iteritems' (in py3.5 should be 'items')
I think is better that you post your python version in readme.md or some file, It can help people more easy to update the code to their working environment.

**Comment by akar43** [comment]
Thanks for the observation and sorry for not mentioning that this codebase had been developed in Python 2.7. I will add this to the Readme and if I get some time upgrade it to Python 3.
