### ISSUE TITLE
Rendering Code

### ISSUE THREAD

**Issue by BornInWater** [akar43/lsm#8]
Hi,

I downloaded the data that has been provided. Thanks for that!
But, I wanted images at more azimuths and elevations and with closer camera parameters. So, could you provide the rendering code that you used to generate the renders?
Thanks

**Comment by akar43** [comment]
Hello,
The blender based rendering code used to generate the dataset should be present [here](https://github.com/shubhtuls/snetRenderer). Unfortunately, I do not have the exact pose parameter files used to generate the dataset provided with the paper but it should not be too hard to specify pose parameters according to your specifications to the renderer.

**Comment by BornInWater** [comment]
Thanks!

**Comment by BornInWater** [comment]
Hey @akar43 The repo you linked to does not seem to be the same as the one used for generating the data you have provided right? It cant produce depth maps.
