### ISSUE TITLE
404 when run prepare_data.sh

### ISSUE THREAD

**Issue by kelly-xuxixi** [akar43/lsm#9]
Hi,

Seems the data is not in the page anymore.

--2019-04-30 00:33:11--  http://people.eecs.berkeley.edu/~akar/lsm/shapenet_release.tar.gz
Resolving people.eecs.berkeley.edu (people.eecs.berkeley.edu)... 128.32.189.73
Connecting to people.eecs.berkeley.edu (people.eecs.berkeley.edu)|128.32.189.73|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://abhishekkar.info/lsm/shapenet_release.tar.gz [following]
--2019-04-30 00:33:11--  https://abhishekkar.info/lsm/shapenet_release.tar.gz
Resolving abhishekkar.info (abhishekkar.info)... 185.199.108.153, 185.199.110.153
Connecting to abhishekkar.info (abhishekkar.info)|185.199.108.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-04-30 00:33:11 ERROR 404: Not Found.

**Comment by akar43** [comment]
Please use [this](https://drive.google.com/open?id=17GjULuQZsn-s92PQFQSBzezDkonowIxR) link to download the release dataset and extract it. My Berkeley webpage expired and files are now hosted on Google Drive. `wget` does not work on Google drive links and they need to be manually downloaded for now. I will update the instructions in the README as well.
